* Einführung in das Modul /Modellierung Qualitativer Daten/ (MQD)

In diesem Modul lernen wir, wie qualitative Daten auf der Grundlage von Texten modelliert werden können. Zu diesem Zweck verwenden wir die folgenden Werkzeuge:

- MTA als Anwendung für die Modellierung der Daten;
- Python (3.x), um MTA zu installieren und durchzuführen;
- Emacs als Textverarbeitungsprogramm und als Anwendung für die Automatisierung von /workflows/ (optional);
- tgpt als Anwendung zur Befragung einer KI, um Vorschläge zur Deutung der Ergebnisse zu erhalten.

* Inhalte des Moduls

Wir beschäftigen uns mit den folgenden Inhalten:

- /Methoden und Techniken der Modellierung von qualitativen Daten/: es sind viele Ansätze zum Umgang mit qualitativen Daten (Texte, Ton, Bilder), die auf der Ebene der theoretischen Annahmen, der Methoden und Techniken unterschiedlich sind, selbst wenn sie zu gemeinsamen Zielen konvergieren; in diesem Modul werden wir uns damit beschäftigen, um zu wissen, wieso es heute Sinn macht, sich mit automatisierten Methoden der Deutung von qualitativen Daten zu beschäftigen.
- /MTA/: wir verwenden eine Anwendung mit Algorithmen zur Schätzung der besten Modelle für unsere Daten; Algorithmen produzieren Klassifikationsmuster, die Daten unterschiedlich klassifizieren. Deshalb müssen wir uns mit der Art und Weise der Klassifikation vertraut machen, die solche Algorithmen vornehmen, und dies machen wir in Bezug auf die Algorithmen, die MTA verwendet.
- /Praktische Beispiele/: wir verwenden Datensätze vom unterschiedlichen Umfang, die wir zusammen im Rahmen der Sitzungen auswerten. Somit kann besser verstanden werden, wie der analytische Prozess funktioniert und je nach Datensatz angepasst werden muss.
- /Ergebnisse darstellen und kommunizieren/: im Rahmen von unseren Analysen generieren wir Abbildungen von den Ergebnissen. Wir lernen, wie wir diese Abbildungen verbessern können, damit analytische Ergebnisse vereinfacht für ein breites Publikum verstanden werden können.
- /Workflows/ (optional): wir zeigen ebenfalls, wie der analytische Prozess als /workflow/ geschrieben werden kann. Solche /workflow/ werden nach dem Ansatz der /literate programming/ geschrieben, darin wir einleiten werden. Diese /workflow/ dienen der Transparenz und der Reproduzierbarkeit der Analyse.

* Voraussetzungen

Dieses Modul setzt eine bestimmte Vertrautheit mit der Informatik, mit Anwendungen und Programmiersprachen und mit der Statistik.

Es setzt ebenfalls eine Bereitschaft, unterschiedliche Werkzeuge zu experimentieren und sich in eine unbekannte Landschaft zu trauen.

* Nächster Schritt

Im nächsten Schritt beschäftigen wir uns mit den [[./Lecture-2-de.org][Methoden und Techniken der Modellierung von qualitativen Daten]].
