* Modellierung von qualitativen Daten mit MTA. Zeitdimension und Semantik

In dieser Sitzung greifen wir auf unseren Ansatz des /workflow/ zurück, um weitere Eigenschaften von MTA zu explorieren. Wir modellieren Daten zur Berichterstattung von Covid-19 in der Presse im Februar 2022 bzw. vom 12.02.2022 bis Ende des Monates in verschiedenen deutschen Zeitungen.

Dieses /workflow/ kann wie eine Anwendung verwendet werden. Erforderlich dafür ist die Installation vom Texteditor Emacs mit Org-mode (ab emacs-28 ist Org-mode mit dem Texteditor geliefert und muss nicht separat installiert werden). Dieses /workflow/ kann auf der Kommandozeile mit dem folgenden Skript 'tm-cov.sh' ausgeführt werden. Ein solcher Skript wird im Arbeitsordner hergestellt, den wir mit dem folgenden Code-Block definieren (Pfad anpassen):

#+name: user-path
#+begin_src shell :var user="/home/cpsoz/TM-WS-25" :results silent
  mkdir $user/TM-Analyse-2
#+end_src

Unsere Analyse wird in diesem Ordner 'TM-Analyse-2' stattfinden. Dort stellen wir einen Ordner 'TM-Skripten' für die Skripten, die wir im Rahmen von diesem /workflow/ schreiben, und wir definieren den vollständigen Pfad zum Ordner 'TM-Analyse' als neuen Benutzerpfad (Pfad anpassen):

#+name: nuser
#+begin_src shell :var nuserpath="/home/cpsoz/TM-WS-25/TM-Analyse-2" :results silent
  echo $nuserpath
#+end_src

#+name: tm-skripten
#+begin_src shell :var userpath=nuser :results silent
  mkdir $userpath/TM-Skripten
#+end_src

Dann schreiben wir den 'tm-cov.sh' Skript wie folgt:

#+begin_src shell :results silent :var user=nuser
  touch $user/tm-cov.sh
  echo "#!/bin/bash" >> $user/tm-cov.sh
  echo "emacs /home/cpsoz/Gitub/mta-tutorial/Org/Lecture-5-de.org --batch -l /home/cpsoz/.emacs.d/init.el --eval \"(setq org-confirm-babel-evaluate nil)\" --eval \"(org-babel-execute-buffer)\"" >> $user/tm-cov.sh
  chmod +x $user/tm-cov.sh
#+end_src

Dieser Skript führt alle Code-Blöcke in diesem /workflow/ aus. Er kann entsprechend mit bash verwendet werden, wie etwa: bash tm-cov.sh oder ./tm-cov.sh. Ohne Skript kann dieses /worflow/ von einem Terminal mit

~emacs /home/cpsoz/Gitub/mta-tutorial/Org/Lecture-5-de.org --batch -l /home/cpsoz/.emacs.d/init.el --eval "(setq org-confirm-babel-evaluate nil)" --eval "(org-babel-execute-buffer)"~

ausgeführt werden. MTA kopieren wir dann zu unserem TM-Skripten Ordner, um die Analyse durchzuführen.

#+name: mta-copy
#+begin_src shell :var mtap="/home/cpsoz/Github/mta-app" :var user=nuser :results silent
  cp $mtap/MTA.py $user/TM-Skripten
#+end_src

* TM-Analyse. Training der Modelle

Wir trainieren MTA auf die Dateien, die wir in einem Ordner 'Stuff3' gespeichert haben. Wir schreiben einen ersten Code-Block, um den Ordner 'Stuff3' als Variable in den nachfolgenden Blöcken zu definieren (Pfad anpassen):

#+name: rechpfad
#+begin_src shell :var rechpath="/home/cpsoz/Github/mta-tutorial/Stuff3" :results silent
  echo $rechpath
#+end_src

Wir müssen auch bedenken, dass wir für MTA eine Stopwords-Liste brauchen (im Ordner 'Stopwords'). Es sind Stop-Wörter, die in unserem Fall deutsche Wörter sind und sich im folgenden Ordner befinden (Pfad anpassen):

#+name: stops
#+begin_src shell :var stopwords="/home/cpsoz/Github/mta-tutorial/Stopwords" :results silent
  echo $stopwords
#+end_src

Wir [[https://github.com/cp1972/mta-app/blob/main/automate.md][automatisieren]] die Ausführung von MTA mit der folgenden 'mta-train.txt'-Datei, die wir in unserem 'TM-Skripten' Ordner speichern:

#+name: autotrain-01
#+begin_src shell :var user=nuser :var rech=rechpfad :var stopw=stops :results silent
  touch $user/TM-Skripten/mta-train.txt
  echo $rech"/*" >> $user/TM-Skripten/mta-train.txt
  echo "y" >> $user/TM-Skripten/mta-train.txt
  echo $stopw"/de.txt" >> $user/TM-Skripten/mta-train.txt
  echo "5" >> $user/TM-Skripten/mta-train.txt
  echo "n" >> $user/TM-Skripten/mta-train.txt
  echo "de" >> $user/TM-Skripten/mta-train.txt
  echo "a" >> $user/TM-Skripten/mta-train.txt
  echo "1" >> $user/TM-Skripten/mta-train.txt
  echo "y" >> $user/TM-Skripten/mta-train.txt
  echo "15" >> $user/TM-Skripten/mta-train.txt
  echo "7" >> $user/TM-Skripten/mta-train.txt
  echo "n" >> $user/TM-Skripten/mta-train.txt
  echo "0" >> $user/TM-Skripten/mta-train.txt
#+end_src

Diese Datei trainiert MTA mit Modellen, die von 2 bis 15 Topics reichen. Entsprechend führen wir MTA mit dem folgenden Code-Block aus:

#+name: trainmta
#+begin_src shell :var user=nuser :results none
  cat $user/TM-Skripten/mta-train.txt | python3 $user/TM-Skripten/MTA.py
#+end_src

Aus den Ergebnissen von MTA in der Datei 'Summary*.log' übernehmen wir die relevanten Informationen zur optimalen Anzahl der Topics je Kreuzvalidierungsmethode, die MTA verwendet. Wir übernehmen auch die Information zu der besten Anzahl der Topics nach dem Cophenet Korrelationskoeffizient. Wir speichern diese Informationen in einer Datei 'TM-train-scores.txt'.

#+name: trainscores
#+begin_src shell :var mtadir="/home/cpsoz/Github/mta-tutorial/Org" :var user=nuser :results silent
  echo " " >> $user/TM-train-scores.txt
  cat $mtadir/MTA-Results*/Summary*.log | sed -n '/Elbow /,/Correlation values LDA/p' | awk 'NF' | awk '{$1=$1;print}' >> $user/TM-train-scores.txt
  echo "------" >> $user/TM-train-scores.txt
  echo " " >> $user/TM-train-scores.txt
  find $mtadir -type d -name "MTA-Results*" -exec rm -r {} +
#+end_src

Wir drucken in dieser Datei alle Ergebnisse aus der Datei 'TM-train-scores.txt' mit dem folgenden Code-Block.

#+name: mta-scores
#+begin_src shell :var user=nuser :results drawer
    cat $user/TM-train-scores.txt
#+end_src

#+RESULTS: mta-scores
:results:

Elbow | No optimal topic
Silhouette | Optimal topics, better to worst: 5 6 8 10 11 12 13
Calinski Harabasz | No optimal topic
Davies Bouldin | Optimal topics, better to worst: 3 5 7 8 9 10 11 12 13 14
NMF-Cophenet | Optimal topics, better to worst: 4 5 7 8 9
Correlation values NMF-Cophenet: (0.716109566486473, 0.6179506131579492, 0.6902732151002392, 0.6583955693271775, 0.7208821961680739)
LDA-Cophenet | Optimal topics, better to worst: 3 5 6 7 8 9 10 12 14
Correlation values LDA-Cophenet: (0.9274421873051646, 0.937363992468951, 0.9191851504436633, 0.9591411056925253, 0.9563689757438678, 0.9640684092895591, 0.9143581342924882, 0.9520142005555593, 0.9286992531527984)
------

:end:

Wir können jetzt die Dateien mit der optimalen Topics-Anzahl modellieren.

* Modellierung

Dafür stellen wir eine veränderte Version von unserem Code-Block 'autotrain-01', die wir 'autotest-01' umbenennen und anpassen. Im Vergleich zu unserem letzten /workflow/ werden wir in dieser Datei Zeile addieren, die auf zwei weitere Optionen von MTA verbunden sind. Die erste Option bieten an, die Entwicklung der Topics in der Zeit zu beobachten. Die zweite Option bietet an, eine Rekonstruktion der semantischen Kontexte, in denen ausgewählte Begriffe eingebettet sind. In diesem letzten Fall interessiert uns, ob die vier Begriffe Covid, Corona, Virus und China in Bezug auf selbe semantischen Kontexte verwendet werden, oder ob sie auf unterschiedliche semantische Kontexte verweisen. Damit erhalten wir auch eine visuelle Darstellung von diesen Kontexten, die über die Größe und Dichte von solchen Kontexten informiert.

#+name: autotest-01
#+begin_src shell :var user=nuser :var rech=rechpfad :var stopw=stops :results silent
  touch $user/TM-Skripten/mta-test.txt
  echo $rech"/*" >> $user/TM-Skripten/mta-test.txt
  echo "y" >> $user/TM-Skripten/mta-test.txt
  echo $stopw"/en.txt" >> $user/TM-Skripten/mta-test.txt
  echo "5" >> $user/TM-Skripten/mta-test.txt
  echo "n" >> $user/TM-Skripten/mta-test.txt
  echo "de" >> $user/TM-Skripten/mta-test.txt
  echo "a" >> $user/TM-Skripten/mta-test.txt
  echo "1" >> $user/TM-Skripten/mta-test.txt
  echo "n" >> $user/TM-Skripten/mta-test.txt
  echo "7" >> $user/TM-Skripten/mta-test.txt
  echo "n" >> $user/TM-Skripten/mta-test.txt
  echo "2" >> $user/TM-Skripten/mta-test.txt
  echo "22" >> $user/TM-Skripten/mta-test.txt
  echo "y" >> $user/TM-Skripten/mta-test.txt
  echo "4" >> $user/TM-Skripten/mta-test.txt
  echo "covid corona virus china" >> $user/TM-Skripten/mta-test.txt
  echo "n" >> $user/TM-Skripten/mta-test.txt
  echo "5" >> $user/TM-Skripten/mta-test.txt
  echo "n" >> $user/TM-Skripten/mta-test.txt
  echo "n" >> $user/TM-Skripten/mta-test.txt
  echo "0" >> $user/TM-Skripten/mta-test.txt
#+end_src

Mit dieser Datei führen wir MTA aus mit dem folgenden Code-Block:

#+name: testmta
#+begin_src shell :var user=nuser :results none
  source .venv/bin/activate
  cat $user/TM-Skripten/mta-test.txt | python3 $user/TM-Skripten/MTA.py
#+end_src

Wir schaffen einen Ordner 'MTA-Results' im Ordner TM-Analyse, um dort die Ergebnisse aus der Modellierung für jeden Subordner vom Ordner 'Rechenzentren' zu speichern:

#+name: mtaresults
#+begin_src shell :var user=nuser :var mtadir="/home/cpsoz/Github/mta-tutorial/Org" :results none
  mkdir $user/MTA-Results
  mv $mtadir/MTA* $user/MTA-Results/
#+end_src

Wir können jetzt die Ergebnisse interpretieren.
